[build]
command = "npm run build"
publish = "build"
functions = "netlify/functions"

[[_redirects]]
from = "/twitch/webhook"
to = "/.netlify/functions/twitch-webhook"
status = 200

[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Twitch-Eventsub-Message-Signature"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
