import { mdsvex } from 'mdsvex';
import adapter from '@sveltejs/adapter-vercel';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import remarkGfm from 'remark-gfm';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  extensions: ['.svelte', '.md', '.svx'],
  preprocess: [
    vitePreprocess(),
    mdsvex({
      extensions: ['.md', '.svx'],
      remarkPlugins: [remarkGfm],
    }),
  ],
  kit: {
    adapter: adapter({
      csp: {
        mode: 'hash',
        directives: {
          'default-src': ['self'],
          'script-src': [
            'self',
            'unsafe-inline',
            'unsafe-eval',
            'ws://localhost:5173/',
            // YouTube & Google Ad domains
            'https://www.youtube.com',
            'https://www.google.com',
            'https://googleads.g.doubleclick.net',
            'https://googlesyndication.com',
            'https://www.googlesyndication.com',
            'https://tpc.googlesyndication.com',
            'https://www.googletagmanager.com',
            'https://googletagmanager.com',
            'https://s.ytimg.com',
            'https://www.gstatic.com',
            'https://pagead2.googlesyndication.com',
            'https://partner.googleadservices.com',
            'https://securepubads.g.doubleclick.net',
            'https://yt3.ggpht.com',
            'https://www.youtube-nocookie.com',
            'https://doubleclick.net',
            'https://googleadservices.com',
            'https://googletag.com',
            'https://imasdk.googleapis.com',
            // Twitch core domains
            'https://gql.twitch.tv',
            'https://embed.twitch.tv',
            'https://player.twitch.tv',
            'https://www.twitch.tv',
            'https://id.twitch.tv',
            'https://passport.twitch.tv',
            'https://static.twitchcdn.net',
            'https://assets.twitch.tv',
            'https://d2v02itv0y9u9t.cloudfront.net',
            'https://*.cloudfront.net',
            'https://cvp.twitch.tv',
            'https://spade.twitch.tv',
            'https://pubsub-edge.twitch.tv',
            'https://video-weaver.*.hls.ttvnw.net',
            'https://usher.ttvnw.net',
            // Twitch ad-specific domains - CRITICAL FOR ADS
            'https://ads.twitch.tv',
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
            'https://c.amazon-adsystem.com',
            'https://fls-na.amazon-adsystem.com',
            'https://aax.amazon-adsystem.com',
            'https://completion.amazon.com',
            'https://unagi.amazon.com',
            'https://z-na.amazon-adsystem.com',
            'https://rcm-na.amazon-adsystem.com',
            'https://advertising.amazon.com',
            'https://dsp.amazon.com',
            'https://prod.advertising.amazon.com',
            // Additional Amazon DSP domains
            'https://amazon.com',
            'https://images-na.ssl-images-amazon.com',
            'https://m.media-amazon.com',
            'https://images-na.ssl-images-amazon.com',
            // IVS (Interactive Video Service) - Amazon's video streaming service used by Twitch
            'https://ivs.amazonaws.com',
            'https://d2nvs31859zcd8.cloudfront.net',
            'https://d1m7jfoe9zdc1j.cloudfront.net',
            // Additional Twitch ad networks
            'https://pubads.g.doubleclick.net',
            'https://tpc.googlesyndication.com',
            'https://www.googletagservices.com',
            'https://googletagservices.com',
            // Supabase
            'https://hguqxixjgwazwsuvhkmo.supabase.co',
          ],
          'frame-src': [
            'self',
            // YouTube & Google Ad domains
            'https://www.youtube.com',
            'https://www.google.com',
            'https://googleads.g.doubleclick.net',
            'https://googlesyndication.com',
            'https://www.googlesyndication.com',
            'https://tpc.googlesyndication.com',
            'https://securepubads.g.doubleclick.net',
            'https://googleadservices.com',
            'https://www.googleadservices.com',
            'https://www.youtube-nocookie.com',
            'https://doubleclick.net',
            'https://imasdk.googleapis.com',
            'https://pubads.g.doubleclick.net',
            'https://googletagservices.com',
            // Twitch core domains
            'https://embed.twitch.tv',
            'https://player.twitch.tv',
            'https://www.twitch.tv',
            'https://id.twitch.tv',
            'https://passport.twitch.tv',
            // Twitch ad-specific domains - CRITICAL FOR AD FRAMES
            'https://ads.twitch.tv',
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
            'https://c.amazon-adsystem.com',
            'https://fls-na.amazon-adsystem.com',
            'https://aax.amazon-adsystem.com',
            'https://completion.amazon.com',
            'https://unagi.amazon.com',
            'https://z-na.amazon-adsystem.com',
            'https://rcm-na.amazon-adsystem.com',
            'https://advertising.amazon.com',
            'https://dsp.amazon.com',
            'https://prod.advertising.amazon.com',
            // IVS domains
            'https://ivs.amazonaws.com',
            'https://d2nvs31859zcd8.cloudfront.net',
            'https://d1m7jfoe9zdc1j.cloudfront.net',
          ],
          'child-src': [
            'self',
            'https://embed.twitch.tv',
            'https://player.twitch.tv',
            'https://www.twitch.tv',
            'https://ads.twitch.tv',
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
            'https://c.amazon-adsystem.com',
            'https://fls-na.amazon-adsystem.com',
            'https://aax.amazon-adsystem.com',
            'https://googleads.g.doubleclick.net',
            'https://googlesyndication.com',
            'https://doubleclick.net',
            'https://imasdk.googleapis.com',
            'https://pubads.g.doubleclick.net',
          ],
          'frame-ancestors': [
            'self',
            'https://embed.twitch.tv',
            'https://player.twitch.tv',
            'https://www.twitch.tv',
          ],
          'connect-src': [
            'self',
            // YouTube & Google Ad domains
            'https://www.youtube.com',
            'https://www.google.com',
            'https://googleads.g.doubleclick.net',
            'https://googlesyndication.com',
            'https://www.googlesyndication.com',
            'https://tpc.googlesyndication.com',
            'https://www.googletagmanager.com',
            'https://stats.g.doubleclick.net',
            'https://cm.g.doubleclick.net',
            'https://securepubads.g.doubleclick.net',
            'https://pagead2.googlesyndication.com',
            'https://partner.googleadservices.com',
            'https://yt3.ggpht.com',
            'https://www.youtube-nocookie.com',
            'https://imasdk.googleapis.com',
            'https://doubleclick.net',
            'https://googleadservices.com',
            'https://googletag.com',
            'https://pubads.g.doubleclick.net',
            'https://googletagservices.com',
            // Twitch core domains
            'https://api.twitch.tv',
            'https://gql.twitch.tv',
            'https://usher.ttvnw.net',
            'https://www.twitch.tv',
            'https://id.twitch.tv',
            'https://passport.twitch.tv',
            'https://static.twitchcdn.net',
            'https://assets.twitch.tv',
            'https://d2v02itv0y9u9t.cloudfront.net',
            'https://*.cloudfront.net',
            'wss://irc-ws.chat.twitch.tv',
            'wss://pubsub-edge.twitch.tv',
            'https://cvp.twitch.tv',
            'https://spade.twitch.tv',
            'https://pubsub-edge.twitch.tv',
            'https://video-weaver.*.hls.ttvnw.net',
            // Twitch ad-specific domains - CRITICAL FOR AD API CALLS
            'https://ads.twitch.tv',
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
            'https://c.amazon-adsystem.com',
            'https://fls-na.amazon-adsystem.com',
            'https://aax.amazon-adsystem.com',
            'https://completion.amazon.com',
            'https://unagi.amazon.com',
            'https://z-na.amazon-adsystem.com',
            'https://rcm-na.amazon-adsystem.com',
            'https://advertising.amazon.com',
            'https://dsp.amazon.com',
            'https://prod.advertising.amazon.com',
            // IVS domains
            'https://ivs.amazonaws.com',
            'https://d2nvs31859zcd8.cloudfront.net',
            'https://d1m7jfoe9zdc1j.cloudfront.net',
            // Supabase
            'https://hguqxixjgwazwsuvhkmo.supabase.co',
            // Development
            'ws://localhost:5173',
          ],
          'img-src': [
            'self',
            'data:',
            'blob:',
            // YouTube & Google Ad domains
            'https://i.ytimg.com',
            'https://s.ytimg.com',
            'https://www.google.com',
            'https://googleads.g.doubleclick.net',
            'https://googlesyndication.com',
            'https://www.googlesyndication.com',
            'https://tpc.googlesyndication.com',
            'https://cm.g.doubleclick.net',
            'https://stats.g.doubleclick.net',
            'https://securepubads.g.doubleclick.net',
            'https://pagead2.googlesyndication.com',
            'https://www.gstatic.com',
            'https://yt3.ggpht.com',
            'https://www.youtube-nocookie.com',
            'https://pubads.g.doubleclick.net',
            // Twitch core domains
            'https://static-cdn.jtvnw.net',
            'https://clips-media-assets2.twitch.tv',
            'https://vod-secure.twitch.tv',
            'https://vod-metro.twitch.tv',
            'https://*.cloudfront.net',
            'https://static.twitchcdn.net',
            'https://assets.twitch.tv',
            // Twitch ad-specific domains - CRITICAL FOR AD IMAGES
            'https://ads.twitch.tv',
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
            'https://c.amazon-adsystem.com',
            'https://fls-na.amazon-adsystem.com',
            'https://aax.amazon-adsystem.com',
            'https://completion.amazon.com',
            'https://unagi.amazon.com',
            'https://z-na.amazon-adsystem.com',
            'https://rcm-na.amazon-adsystem.com',
            'https://advertising.amazon.com',
            'https://dsp.amazon.com',
            'https://prod.advertising.amazon.com',
            'https://images-na.ssl-images-amazon.com',
            'https://m.media-amazon.com',
            // IVS domains
            'https://ivs.amazonaws.com',
            'https://d2nvs31859zcd8.cloudfront.net',
            'https://d1m7jfoe9zdc1j.cloudfront.net',
          ],
          'media-src': [
            'self',
            'blob:',
            'data:',
            // YouTube & Google domains
            'https://www.youtube.com',
            'https://googlevideo.com',
            'https://*.googlevideo.com',
            'https://googleads.g.doubleclick.net',
            'https://www.youtube-nocookie.com',
            // Twitch core domains
            'https://vod-secure.twitch.tv',
            'https://vod-metro.twitch.tv',
            'https://clips-media-assets2.twitch.tv',
            'https://*.cloudfront.net',
            'https://video-weaver.*.hls.ttvnw.net',
            // Twitch ad-specific domains - CRITICAL FOR AD VIDEO/AUDIO
            'https://ads.twitch.tv',
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
            'https://c.amazon-adsystem.com',
            'https://fls-na.amazon-adsystem.com',
            'https://aax.amazon-adsystem.com',
            // IVS domains for video delivery
            'https://ivs.amazonaws.com',
            'https://d2nvs31859zcd8.cloudfront.net',
            'https://d1m7jfoe9zdc1j.cloudfront.net',
          ],
          'style-src': [
            'self',
            'unsafe-inline',
            // YouTube & Google domains
            'https://www.youtube.com',
            'https://fonts.googleapis.com',
            'https://googleads.g.doubleclick.net',
            'https://googlesyndication.com',
            'https://www.googlesyndication.com',
            'https://www.gstatic.com',
            'https://www.youtube-nocookie.com',
            // Twitch domains
            'https://static.twitchcdn.net',
            'https://assets.twitch.tv',
            // Ad-related domains
            'https://amazon-adsystem.com',
            'https://s.amazon-adsystem.com',
          ],
          'font-src': [
            'self',
            'https://fonts.gstatic.com',
            'https://www.youtube.com',
            'https://www.gstatic.com',
            'https://static.twitchcdn.net',
            'https://assets.twitch.tv',
          ],
          'worker-src': ['self', 'blob:'],
          'object-src': ['none'],
        },
      },
    }),
  },
};

export default config;
