import { youtube } from "@googleapis/youtube";
import { createClient } from "@supabase/supabase-js";
import { randomBytes } from "crypto";
import { CHANNEL_INFO, CHANNEL_SOURCES, ChannelSource } from "../channel";

const MAX_RESULTS = 50;

export const populatePlaylists = async ({
  source,
}: {
  source: ChannelSource;
}) => {
  const supabaseApiKey = process.env.SUPABASE_SERVICE_API_KEY_PROD;
  const supabaseUrl = process.env.PUBLIC_SUPABASE_URL_PROD;
  if (!supabaseApiKey || !supabaseUrl) {
    throw new Error("Could not find Supabase env.");
  }

  const supabaseClient = createClient(supabaseUrl, supabaseApiKey);

  if (!source) {
    throw new Error("Request body must contain the source of the content.");
  }
  const { id: channelId } = CHANNEL_INFO[source];
  if (!channelId) {
    throw new Error(`channelId not found for source: ${source}`);
  }

  const email = `${source}@bombify.net`;
  // Securely generate a random password (never used for login)
  const password = randomBytes(32).toString("base64url");

  const username = source;

  // Call the RPC and extract the userId
  const { data: userId, error: userError } = await supabaseClient.rpc(
    "create_user",
    {
      email,
      password,
      username,
    },
  );

  if (!userId) {
    console.error("Error creating or fetching user:", userError, userId);
    throw new Error("Failed to create or fetch user for source.");
  } else {
    console.log(`User for ${email}: ${userId}`);
  }

  const youtubeClient = youtube({
    version: "v3",
    auth: process.env.GOOGLE_API_KEY,
  });

  let pageToken: string | null | undefined;
  do {
    const { data } = await youtubeClient.playlists.list({
      part: ["id", "snippet"],
      channelId,
      maxResults: MAX_RESULTS,
      ...(pageToken && { pageToken }),
    });

    const { nextPageToken, items } = data;

    if (!items || items.length === 0) {
      console.warn(`No playlists found for: ${source}`);
      break;
    }

    for (const item of items) {
      // Use autogenerated ID
      const playlistObj = {
        youtube_id: item.id,
        name: item.snippet?.title ?? "Untitled",
        created_by: userId,
        thumbnail_url: item.snippet?.thumbnails?.default?.url ?? null,
        thumbnail_maxres_url: item.snippet?.thumbnails?.maxres?.url ?? null,
        type: "Official",
      };

      // Upsert playlist and get the row (to get the internal playlist id)
      const { data: upsertedPlaylist, error: playlistError } =
        await supabaseClient
          .from("playlists")
          .upsert(playlistObj, {
            onConflict: "youtube_id",
          })
          .select()
          .single();

      if (playlistError || !upsertedPlaylist) {
        console.error("Error upserting playlist:", playlistError, playlistObj);
        continue;
      }

      // Now fetch video IDs for this playlist from YouTube
      let videoPageToken: string | null | undefined;
      const allVideoIds: string[] = [];
      do {
        const { data: playlistItemsData } =
          await youtubeClient.playlistItems.list({
            part: ["contentDetails"],
            playlistId: item.id!,
            maxResults: 50,
            ...(videoPageToken && { pageToken: videoPageToken }),
          });
        const { items: videoItems, nextPageToken: nextVideoPageToken } =
          playlistItemsData ?? {};

        if (videoItems && videoItems.length > 0) {
          allVideoIds.push(
            ...videoItems
              .map((v) => v.contentDetails?.videoId)
              .filter((videoId): videoId is string => !!videoId),
          );
        }

        videoPageToken = nextVideoPageToken;
      } while (videoPageToken);

      if (allVideoIds.length === 0) {
        console.log(
          `No videos found for playlist ${playlistObj.name}. Skipping playlist_videos insert.`,
        );
        continue;
      }

      // Insert directly into playlist_videos
      let videoPosition = 1;
      for (const videoId of allVideoIds) {
        // You may want to check for existing records or handle constraints as appropriate for your app
        const { error: insertError } = await supabaseClient
          .from("playlist_videos")
          .upsert(
            {
              playlist_id: upsertedPlaylist.id,
              video_id: videoId,
              video_position: videoPosition,
            },
            {
              onConflict: "playlist_id,video_id",
            },
          );

        if (insertError) {
          console.error(
            `Error inserting playlist_video for playlist ${playlistObj.name}, video ${videoId}:`,
            insertError,
          );
        }
        videoPosition++;
      }

      console.log(
        `Inserted/updated ${allVideoIds.length} playlist_videos for playlist ${playlistObj.name}.`,
      );
    }

    pageToken = nextPageToken;
  } while (pageToken);
};
