import { youtube } from "@googleapis/youtube";
import { createClient } from "@supabase/supabase-js";
import { randomBytes } from "crypto";
import { CHANNEL_INFO, ChannelSource } from "../channel";

const MAX_RESULTS = 5; // Reduced from 50 since playlists are not added frequently

export const populatePlaylists = async ({
  source,
}: {
  source: ChannelSource;
}) => {
  const supabaseApiKey = process.env.SUPABASE_SERVICE_API_KEY_PROD;
  const supabaseUrl = process.env.PUBLIC_SUPABASE_URL_PROD;
  if (!supabaseApiKey || !supabaseUrl) {
    const errMsg = "Could not find Supabase env.";
    console.error(JSON.stringify({ stage: "init", error: errMsg }));
    throw new Error(errMsg);
  }

  const supabaseClient = createClient(supabaseUrl, supabaseApiKey);

  if (!source) {
    const errMsg = "Request body must contain the source of the content.";
    console.error(JSON.stringify({ stage: "init", error: errMsg }));
    throw new Error(errMsg);
  }

  const { id: channelId, uploadPlaylistId } = CHANNEL_INFO[source];
  if (!channelId) {
    const errMsg = `channelId not found for source: ${source}`;
    console.error(JSON.stringify({ stage: "init", source, error: errMsg }));
    throw new Error(errMsg);
  }

  try {
    const email = `${source}@bombify.net`;
    // Securely generate a random password (never used for login)
    const password = randomBytes(32).toString("base64url");
    const username = source;

    // Call the RPC and extract the userId
    const { data: userId, error: userError } = await supabaseClient.rpc(
      "create_user",
      {
        email,
        password,
        username,
      },
    );

    if (!userId) {
      console.error(JSON.stringify({
        stage: "create_user",
        source,
        error: userError,
      }));
      throw new Error("Failed to create or fetch user for source.");
    } else {
      console.log(JSON.stringify({
        stage: "create_user",
        message: `User for ${email}: ${userId}`,
        source,
      }));
    }

    const youtubeClient = youtube({
      version: "v3",
      auth: process.env.GOOGLE_API_KEY,
    });

    const youtubePlaylistIds = new Set<string>();

    // Step 1: Fetch ALL playlists from YouTube first (excluding uploads playlist)
    let pageToken: string | null | undefined;
    let totalPlaylistsProcessed = 0;
    let uploadsPlaylistSkipped = false;

    do {
      let items;
      try {
        const { data } = await youtubeClient.playlists.list({
          part: ["id", "snippet"],
          channelId,
          maxResults: MAX_RESULTS,
          ...(pageToken && { pageToken }),
        });

        ({ nextPageToken: pageToken, items } = data);

        if (!items || items.length === 0) {
          console.log(JSON.stringify({
            stage: "fetch_youtube_playlists",
            message: `No playlists found for: ${source}`,
            source,
          }));
          break;
        }
      } catch (e) {
        console.error(JSON.stringify({
          stage: "fetch_youtube_playlists",
          source,
          channelId,
          error: e,
        }));
        throw e;
      }

      for (const item of items) {
        if (!item.id) continue;

        // Skip the uploads playlist since it's handled by populateVideos
        if (item.id === uploadPlaylistId) {
          uploadsPlaylistSkipped = true;
          console.log(JSON.stringify({
            stage: "skip_uploads_playlist",
            message: `Skipping uploads playlist ${item.id} as it's handled by populateVideos`,
            source,
            playlistId: item.id,
            playlistName: item.snippet?.title,
          }));
          continue;
        }

        youtubePlaylistIds.add(item.id);
        totalPlaylistsProcessed++;

        // Use autogenerated ID
        const playlistObj = {
          youtube_id: item.id,
          name: item.snippet?.title ?? "Untitled",
          created_by: userId,
          thumbnail_url: item.snippet?.thumbnails?.default?.url ?? null,
          thumbnail_maxres_url: item.snippet?.thumbnails?.maxres?.url ?? null,
          type: "Official",
        };

        // Upsert playlist and get the row (to get the internal playlist id)
        const { data: upsertedPlaylist, error: playlistError } =
          await supabaseClient
            .from("playlists")
            .upsert(playlistObj, {
              onConflict: "youtube_id",
            })
            .select()
            .single();

        if (playlistError || !upsertedPlaylist) {
          console.error(JSON.stringify({
            stage: "upsert_playlist",
            source,
            playlistId: item.id,
            error: playlistError,
            playlistObj,
          }));
          continue;
        }

        // Now fetch video IDs for this playlist from YouTube
        let videoPageToken: string | null | undefined;
        const allVideoIds: string[] = [];
        do {
          try {
            const { data: playlistItemsData } =
              await youtubeClient.playlistItems.list({
                part: ["contentDetails"],
                playlistId: item.id!,
                maxResults: 50,
                ...(videoPageToken && { pageToken: videoPageToken }),
              });
            const { items: videoItems, nextPageToken: nextVideoPageToken } =
              playlistItemsData ?? {};

            if (videoItems && videoItems.length > 0) {
              allVideoIds.push(
                ...videoItems
                  .map((v) => v.contentDetails?.videoId)
                  .filter((videoId): videoId is string => !!videoId),
              );
            }

            videoPageToken = nextVideoPageToken;
          } catch (e) {
            console.error(JSON.stringify({
              stage: "fetch_playlist_videos",
              source,
              playlistId: item.id,
              error: e,
            }));
            throw e;
          }
        } while (videoPageToken);

        if (allVideoIds.length === 0) {
          console.log(JSON.stringify({
            stage: "no_videos_in_playlist",
            message: `No videos found for playlist ${playlistObj.name}. Will clean up any existing playlist_videos.`,
            source,
            playlistId: item.id,
          }));
        }

        // Get existing playlist_videos for this playlist to identify what to delete
        const { data: existingPlaylistVideos, error: existingError } = await supabaseClient
          .from("playlist_videos")
          .select("video_id")
          .eq("playlist_id", upsertedPlaylist.id);

        if (existingError) {
          console.error(JSON.stringify({
            stage: "fetch_existing_playlist_videos",
            source,
            playlistId: item.id,
            internalPlaylistId: upsertedPlaylist.id,
            error: existingError,
          }));
          throw new Error("Failed to fetch existing playlist videos");
        }

        // Find videos to remove (exist in DB but not in YouTube)
        const existingVideoIds = (existingPlaylistVideos || []).map(pv => pv.video_id);
        const videosToRemove = existingVideoIds.filter(videoId => !allVideoIds.includes(videoId));

        // Remove playlist_videos that are no longer in YouTube
        if (videosToRemove.length > 0) {
          const { error: deleteError } = await supabaseClient
            .from("playlist_videos")
            .delete()
            .eq("playlist_id", upsertedPlaylist.id)
            .in("video_id", videosToRemove);

          if (deleteError) {
            console.error(JSON.stringify({
              stage: "delete_stale_playlist_videos",
              source,
              playlistId: item.id,
              internalPlaylistId: upsertedPlaylist.id,
              videosToRemove,
              error: deleteError,
            }));
          } else {
            console.log(JSON.stringify({
              stage: "delete_stale_playlist_videos",
              message: `Removed ${videosToRemove.length} stale videos from playlist ${playlistObj.name}`,
              source,
              playlistId: item.id,
              removedVideoIds: videosToRemove,
            }));
          }
        }

        // Insert/update current playlist_videos
        let videoPosition = 1;
        for (const videoId of allVideoIds) {
          const { error: insertError } = await supabaseClient
            .from("playlist_videos")
            .upsert(
              {
                playlist_id: upsertedPlaylist.id,
                video_id: videoId,
                video_position: videoPosition,
              },
              {
                onConflict: "playlist_id,video_id",
              },
            );

          if (insertError) {
            console.error(JSON.stringify({
              stage: "upsert_playlist_video",
              source,
              playlistId: item.id,
              videoId,
              error: insertError,
            }));
          }
          videoPosition++;
        }

        console.log(JSON.stringify({
          stage: "playlist_processing_complete",
          message: `Processed playlist ${playlistObj.name}: ${allVideoIds.length} videos total, ${videosToRemove.length} removed`,
          source,
          playlistId: item.id,
          totalVideos: allVideoIds.length,
          removedVideos: videosToRemove.length,
        }));
      }
    } while (pageToken);

    // Step 2: Handle playlists that no longer exist on YouTube (excluding uploads playlist)
    // Get all playlists for this user that are "Official" type, excluding uploads playlist
    const { data: existingPlaylists, error: existingPlaylistsError } = await supabaseClient
      .from("playlists")
      .select("id, youtube_id, name")
      .eq("created_by", userId)
      .eq("type", "Official")
      .neq("youtube_id", uploadPlaylistId); // Exclude uploads playlist from cleanup

    if (existingPlaylistsError) {
      console.error(JSON.stringify({
        stage: "fetch_existing_playlists",
        source,
        error: existingPlaylistsError,
      }));
      throw new Error("Failed to fetch existing playlists");
    }

    // Find playlists to remove (exist in DB but not in YouTube, excluding uploads playlist)
    const playlistsToRemove = (existingPlaylists || []).filter(
      playlist => playlist.youtube_id && !youtubePlaylistIds.has(playlist.youtube_id)
    );

    if (playlistsToRemove.length > 0) {
      // First, delete all playlist_videos for these playlists
      for (const playlist of playlistsToRemove) {
        const { error: deletePlaylistVideosError } = await supabaseClient
          .from("playlist_videos")
          .delete()
          .eq("playlist_id", playlist.id);

        if (deletePlaylistVideosError) {
          console.error(JSON.stringify({
            stage: "delete_playlist_videos_for_removed_playlist",
            source,
            playlistId: playlist.id,
            youtubeId: playlist.youtube_id,
            error: deletePlaylistVideosError,
          }));
        }
      }

      // Then delete the playlists themselves
      const playlistIdsToRemove = playlistsToRemove.map(p => p.id);
      const { error: deletePlaylistsError } = await supabaseClient
        .from("playlists")
        .delete()
        .in("id", playlistIdsToRemove);

      if (deletePlaylistsError) {
        console.error(JSON.stringify({
          stage: "delete_removed_playlists",
          source,
          playlistIdsToRemove,
          error: deletePlaylistsError,
        }));
      } else {
        console.log(JSON.stringify({
          stage: "delete_removed_playlists",
          message: `Removed ${playlistsToRemove.length} playlists that no longer exist on YouTube`,
          source,
          removedPlaylists: playlistsToRemove.map(p => ({ id: p.id, name: p.name, youtube_id: p.youtube_id })),
        }));
      }
    }

    console.log(JSON.stringify({
      stage: "sync_complete",
      message: `Playlist sync completed for ${source}. Processed ${totalPlaylistsProcessed} YouTube playlists (skipped uploads playlist), removed ${playlistsToRemove.length} stale playlists`,
      source,
      youtubePlaylistsProcessed: totalPlaylistsProcessed,
      playlistsRemoved: playlistsToRemove.length,
      uploadsPlaylistSkipped,
    }));

  } catch (e) {
    // Final catch-all for unhandled errors
    console.error(JSON.stringify({
      stage: "final",
      source,
      error: e instanceof Error ? e.message : e,
      stack: e instanceof Error ? e.stack : undefined,
    }));
    throw e; // Rethrow to signal Lambda failure
  }
};
