-- Migration: 03_base_tables.sql
-- Purpose: Create core table structures without foreign keys
-- This allows tables to be created in any order before adding relationships
SET
  default_tablespace = '';

SET
  default_table_access_method = "heap";

-- Videos table (no dependencies)
CREATE TABLE IF NOT EXISTS "public"."videos" (
  "id" "text" NOT NULL,
  "source" "public"."source" NOT NULL,
  "title" "text" NOT NULL,
  "description" "text" NOT NULL,
  "published_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  "search_vector" "tsvector",
  "pending_delete" boolean DEFAULT TRUE,
  "duration" "text" DEFAULT ''::"text",
  "thumbnail_url" "text" NOT NULL,
  "thumbnail_webp_url" text,
  "thumbnail_avif_url" text,
  "image_processing_status" public.image_processing_status DEFAULT 'pending',
  "image_processing_updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "views" bigint DEFAULT 0 NOT NULL
);

ALTER TABLE "public"."videos" OWNER TO "postgres";

COMMENT ON COLUMN "public"."videos"."pending_delete" IS 'Pending delete flag is used for detecting and removing deleted videos from YouTube';

COMMENT ON COLUMN "public"."videos"."thumbnail_url" IS 'Primary thumbnail URL for video display and processing source';

COMMENT ON COLUMN "public"."videos"."thumbnail_webp_url" IS 'Supabase Storage path for WebP thumbnail';

COMMENT ON COLUMN "public"."videos"."thumbnail_avif_url" IS 'Supabase Storage path for AVIF thumbnail';

COMMENT ON COLUMN "public"."videos"."image_processing_status" IS 'Status of background image processing for this video';

COMMENT ON COLUMN "public"."videos"."views" IS 'Total number of times this video has been viewed by users';

-- Videos constraints (no foreign keys)
ALTER TABLE ONLY "public"."videos"
ADD CONSTRAINT "videos_pkey" PRIMARY KEY ("id");

-- Playlists table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."playlists" (
  "id" bigint DEFAULT nextval('public.playlists_custom_seq'::regclass) NOT NULL,
  "created_by" uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "name" text NOT NULL,
  "short_id" text DEFAULT NULL NOT NULL,
  "search_vector" tsvector,
  "youtube_id" text DEFAULT NULL,
  "description" text,
  "type" "public"."playlist_type" NOT NULL DEFAULT 'Private',
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "duration_seconds" integer DEFAULT 0,
  "thumbnail_url" text DEFAULT NULL,
  -- Crop dimensions for generating playlist thumbnails from video thumbnail
  "image_properties" jsonb, -- {x: number, y: number, width: number, height: number}
  -- Generated cropped playlist images (stored in Supabase Storage)
  "image_webp_url" text,
  "image_avif_url" text,
  -- Image processing tracking
  "image_processing_status" public.image_processing_status DEFAULT 'pending',
  "image_processing_updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CONSTRAINT "playlists_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "playlists_name_check" CHECK (length("name") <= 50),
  CONSTRAINT "playlists_youtube_id_unique" UNIQUE ("youtube_id"),
  CONSTRAINT "playlists_short_id_key" UNIQUE ("short_id")
);

-- Comments for clarity
COMMENT ON COLUMN "public"."playlists"."thumbnail_url" IS 'Direct thumbnail URL for playlist display';

COMMENT ON COLUMN "public"."playlists"."image_properties" IS 'Crop dimensions {x, y, width, height} for generating playlist image from video thumbnail';

COMMENT ON COLUMN "public"."playlists"."image_webp_url" IS 'Supabase Storage path for cropped playlist image in WebP format';

COMMENT ON COLUMN "public"."playlists"."image_avif_url" IS 'Supabase Storage path for cropped playlist image in AVIF format';

COMMENT ON COLUMN "public"."playlists"."image_processing_status" IS 'Status of background image processing for playlist thumbnail generation';

-- Playlist videos table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."playlist_videos" (
  "playlist_id" bigint NOT NULL,
  "video_id" text NOT NULL,
  "video_position" int2 DEFAULT NULL,
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."playlist_videos_id_seq" START
    WITH
      1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  )
);

COMMENT ON COLUMN "public"."playlist_videos"."video_position" IS 'Ordering of videos added to playlist (1-indexed).';

-- Playlist videos constraints (no foreign keys)
ALTER TABLE ONLY "public"."playlist_videos"
ADD CONSTRAINT "playlist_videos_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."playlist_videos"
ADD CONSTRAINT "unique_playlist_video" UNIQUE ("playlist_id", "video_id");

-- Timestamps table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."timestamps" (
  "id" bigint NOT NULL,
  "user_id" uuid NOT NULL,
  "video_id" "text" NOT NULL,
  "video_start_seconds" numeric,
  "playlist_id" bigint,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  "watched_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  "sorted_by" "public"."playlist_sorted_by" DEFAULT NULL,
  "sort_order" "public"."playlist_sort_order" DEFAULT NULL
);

ALTER TABLE "public"."timestamps" OWNER TO "postgres";

COMMENT ON COLUMN "public"."timestamps"."video_start_seconds" IS 'Offset in seconds to start video playback.';

COMMENT ON COLUMN "public"."timestamps"."watched_at" IS 'Datetime for when the video was last watched.';

-- Timestamps constraints and identity (no foreign keys)
ALTER TABLE "public"."timestamps"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."user_video_timestamps_id_seq" START
  WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."timestamps"
ADD CONSTRAINT "user_video_timestamps_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."timestamps"
ADD CONSTRAINT "unique_user_video" UNIQUE ("user_id", "video_id");

-- Profiles table (without foreign keys initially) - FIXED TYPE REFERENCES
CREATE TABLE IF NOT EXISTS "public"."profiles" (
  "id" uuid NOT NULL,
  "username" text,
  "username_history" jsonb DEFAULT '[]'::jsonb,
  "sources" "public"."source" [] DEFAULT ARRAY[
    'giantbomb',
    'jeffgerstmann',
    'nextlander',
    'remap'
  ]::"public"."source" [],
  "content_description" "public"."content_description" DEFAULT 'BRIEF',
  "content_display" "public"."content_display" DEFAULT 'TILES',
  "avatar_url" text DEFAULT NULL,
  "account_type" public.profile_account_type DEFAULT 'default',
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."profiles"."username_history" IS 'JSON array storing username history with timestamps. Format: [{"username": "old_name", "used_from": "2023-01-01T00:00:00Z", "used_until": "2023-06-01T00:00:00Z"}]';

-- User playlists table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."user_playlists" (
  "id" bigint NOT NULL,
  "user_id" uuid DEFAULT NULL,
  "playlist_position" int2 DEFAULT NULL,
  "sorted_by" "public"."playlist_sorted_by" DEFAULT 'playlistOrder' NOT NULL,
  "sort_order" "public"."playlist_sort_order" DEFAULT 'ascending' NOT NULL,
  "added_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  PRIMARY KEY ("id", "user_id")
);

ALTER TABLE "public"."user_playlists" OWNER TO "postgres";

COMMENT ON COLUMN "public"."user_playlists"."playlist_position" IS 'Ordering of playlists for each user (1-indexed).';
