

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';









CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_hashids" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";






CREATE TYPE "public"."source" AS ENUM (
    'giantbomb',
    'nextlander',
    'jeffgerstmann',
    'remap'
);


ALTER TYPE "public"."source" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."delete_pending_videos"() RETURNS "void"
    LANGUAGE "plpgsql"
    SET search_path = ''
    AS $$BEGIN
    -- Delete associated user_video_timestamps for videos marked for deletion
    DELETE FROM public.timestamps
    WHERE video_id IN (SELECT id FROM public.videos WHERE pending_delete = TRUE);

    -- Delete videos marked for deletion
    DELETE FROM public.videos
    WHERE pending_delete = TRUE;
END;$$;


ALTER FUNCTION "public"."delete_pending_videos"() OWNER TO "postgres";



CREATE OR REPLACE FUNCTION "public"."set_playlist_search_vector"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET search_path = ''
    AS $$BEGIN
  NEW.search_vector := to_tsvector('english', NEW.name);
  RETURN NEW;
END;$$;


ALTER FUNCTION "public"."set_playlist_search_vector"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_short_id"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET search_path = ''
    AS $$
BEGIN
    NEW.short_id := extensions.id_encode(NEW.id);
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."set_short_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_video_search_vector"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET search_path = ''
    AS $$BEGIN
  NEW.search_vector := 
      setweight(to_tsvector('english', NEW.title), 'A') || 
      setweight(to_tsvector('english', NEW.title), 'A') ||  -- Double weight for title
      setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C');  -- Lower weight for description
  RETURN NEW;
END;$$;

ALTER FUNCTION "public"."set_video_search_vector"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_timestamp"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET search_path = ''
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_timestamp"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";



CREATE SEQUENCE IF NOT EXISTS "public"."playlists_custom_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."playlists_custom_seq" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."playlists" (
    "id" bigint DEFAULT nextval('public.playlists_custom_seq'::regclass) NOT NULL,
    "created_by" uuid NOT NULL REFERENCES auth.users(id),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "name" text NOT NULL,
    "short_id" text DEFAULT NULL NOT NULL,
    "search_vector" tsvector,
    "image_url" text,
    "youtube_id" text DEFAULT NULL,
    CONSTRAINT "playlists_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "playlists_name_check" CHECK (length("name") <= 50),
    CONSTRAINT "playlists_youtube_id_unique" UNIQUE ("youtube_id")
);

ALTER TABLE "public"."playlists" OWNER TO "postgres";

COMMENT ON COLUMN "public"."playlists"."name" IS 'Playlist name';

COMMENT ON COLUMN "public"."playlists"."short_id" IS 'Short ID for nicer URLs';

CREATE TABLE IF NOT EXISTS "public"."playlist_videos" (
    "playlist_id" bigint NOT NULL REFERENCES "public"."playlists" ("id") ON DELETE CASCADE,
    "video_id" text NOT NULL, 
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."playlist_videos_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    )
);


ALTER TABLE "public"."playlist_videos" OWNER TO "postgres";



CREATE TABLE IF NOT EXISTS "public"."timestamps" (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "video_id" "text" NOT NULL,
    "video_start_seconds" numeric,
    "playlist_id" bigint REFERENCES public.playlists("id") ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "watched_at" timestamp with time zone,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."timestamps" OWNER TO "postgres";


COMMENT ON COLUMN "public"."timestamps"."video_start_seconds" IS 'Offset in seconds to start video playback.';


COMMENT ON COLUMN "public"."timestamps"."watched_at" IS 'Datetime for when the video was last watched.';


ALTER TABLE "public"."timestamps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_video_timestamps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."videos" (
    "id" "text" NOT NULL,
    "source" "public"."source" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "thumbnail_url" "text" NOT NULL,
    "published_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "search_vector" "tsvector",
    "pending_delete" boolean DEFAULT true,
    "duration" "text" DEFAULT ''::"text",
    "thumbnail_maxres_url" "text"
);


ALTER TABLE "public"."videos" OWNER TO "postgres";


COMMENT ON COLUMN "public"."videos"."pending_delete" IS 'Pending delete flag is used for detecting and removing deleted videos from YouTube';



COMMENT ON COLUMN "public"."videos"."thumbnail_maxres_url" IS 'Max res url';



ALTER TABLE ONLY "public"."playlist_videos"
    ADD CONSTRAINT "playlist_videos_id_key" UNIQUE ("id");





ALTER TABLE ONLY "public"."playlists"
    ADD CONSTRAINT "playlists_short_id_key" UNIQUE ("short_id");



ALTER TABLE ONLY "public"."playlist_videos"
    ADD CONSTRAINT "unique_playlist_video" UNIQUE ("playlist_id", "video_id");



ALTER TABLE ONLY "public"."timestamps"
    ADD CONSTRAINT "unique_user_video" UNIQUE ("user_id", "video_id");



ALTER TABLE ONLY "public"."timestamps"
    ADD CONSTRAINT "user_video_timestamps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."videos"
    ADD CONSTRAINT "videos_id_key" UNIQUE ("id");




CREATE INDEX "idx_user_video_timestamps_video_id" ON "public"."timestamps" USING "btree" ("video_id");



CREATE OR REPLACE TRIGGER "before_insert_set_short_id" BEFORE INSERT ON "public"."playlists" FOR EACH ROW EXECUTE FUNCTION "public"."set_short_id"();



CREATE OR REPLACE TRIGGER "update_playlist_search_vector" BEFORE INSERT OR UPDATE ON "public"."playlists" FOR EACH ROW EXECUTE FUNCTION "public"."set_playlist_search_vector"();



CREATE OR REPLACE TRIGGER "update_user_video_timestamps_updated_at" BEFORE UPDATE ON "public"."timestamps" FOR EACH ROW EXECUTE FUNCTION "public"."update_timestamp"();



CREATE OR REPLACE TRIGGER "update_video_search_vector" BEFORE INSERT OR UPDATE ON "public"."videos" FOR EACH ROW EXECUTE FUNCTION "public"."set_video_search_vector"();



ALTER TABLE ONLY "public"."playlist_videos"
    ADD CONSTRAINT "playlist_videos_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."timestamps"
    ADD CONSTRAINT "user_video_timestamps_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow users to update their own playlists" ON "public"."playlists" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "created_by")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "created_by"));



CREATE POLICY "Authenticated users can insert their own video timestamps" ON "public"."timestamps" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Authenticated users can select their own video timestamps" ON "public"."timestamps" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Authenticated users can update their own video timestamps" ON "public"."timestamps" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."timestamps" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));


CREATE POLICY "Enable insert for users based on created_by" ON "public"."playlists" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "created_by"));



CREATE POLICY "Enable read access for all users" ON "public"."videos" FOR SELECT USING (true);



ALTER TABLE "public"."playlist_videos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."playlists" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."timestamps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."videos" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































































































































































































































































































































































































































































































































































































































GRANT ALL ON FUNCTION "public"."delete_pending_videos"() TO "anon";
GRANT ALL ON FUNCTION "public"."delete_pending_videos"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_pending_videos"() TO "service_role";


GRANT ALL ON FUNCTION "public"."set_playlist_search_vector"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_playlist_search_vector"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_playlist_search_vector"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_short_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_short_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_short_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_video_search_vector"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_video_search_vector"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_video_search_vector"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_timestamp"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_timestamp"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_timestamp"() TO "service_role";




































GRANT ALL ON TABLE "public"."playlist_videos" TO "anon";
GRANT ALL ON TABLE "public"."playlist_videos" TO "authenticated";
GRANT ALL ON TABLE "public"."playlist_videos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."playlist_videos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."playlist_videos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."playlist_videos_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."playlists_custom_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."playlists_custom_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."playlists_custom_seq" TO "service_role";



GRANT ALL ON TABLE "public"."playlists" TO "anon";
GRANT ALL ON TABLE "public"."playlists" TO "authenticated";
GRANT ALL ON TABLE "public"."playlists" TO "service_role";



GRANT ALL ON TABLE "public"."timestamps" TO "anon";
GRANT ALL ON TABLE "public"."timestamps" TO "authenticated";
GRANT ALL ON TABLE "public"."timestamps" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_video_timestamps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_video_timestamps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_video_timestamps_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."videos" TO "anon";
GRANT ALL ON TABLE "public"."videos" TO "authenticated";
GRANT ALL ON TABLE "public"."videos" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
