-- Migration: 03_base_tables.sql
-- Purpose: Create core table structures without foreign keys
-- This allows tables to be created in any order before adding relationships
SET
  default_tablespace = '';

SET
  default_table_access_method = "heap";

-- Videos table (no dependencies)
CREATE TABLE IF NOT EXISTS "public"."videos" (
  "id" "text" NOT NULL,
  "source" "public"."source" NOT NULL,
  "title" "text" NOT NULL,
  "description" "text" NOT NULL,
  "thumbnail_url" "text" NOT NULL,
  "published_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  "search_vector" "tsvector",
  "pending_delete" boolean DEFAULT TRUE,
  "duration" "text" DEFAULT ''::"text",
  "thumbnail_maxres_url" "text"
);

ALTER TABLE "public"."videos" OWNER TO "postgres";

COMMENT ON COLUMN "public"."videos"."pending_delete" IS 'Pending delete flag is used for detecting and removing deleted videos from YouTube';

COMMENT ON COLUMN "public"."videos"."thumbnail_maxres_url" IS 'Max res url';

-- Videos constraints (no foreign keys)
ALTER TABLE ONLY "public"."videos"
ADD CONSTRAINT "videos_pkey" PRIMARY KEY ("id");

-- Playlists table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."playlists" (
  "id" bigint DEFAULT nextval('public.playlists_custom_seq'::regclass) NOT NULL,
  "created_by" uuid NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "name" text NOT NULL,
  "short_id" text DEFAULT NULL NOT NULL,
  "search_vector" tsvector,
  "youtube_id" text DEFAULT NULL,
  "description" text,
  "image_properties" jsonb,
  "type" "public"."playlist_type" NOT NULL DEFAULT 'Private',
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "duration_seconds" integer DEFAULT 0,
  "image_processing_updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "image_processing_status" text DEFAULT NULL,
  "image_url" text,
  "image_webp_url" text,
  "image_avif_url" text,
  CONSTRAINT "playlists_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "playlists_name_check" CHECK (length("name") <= 50),
  CONSTRAINT "playlists_youtube_id_unique" UNIQUE ("youtube_id"),
  CONSTRAINT "playlists_short_id_key" UNIQUE ("short_id")
);

ALTER TABLE "public"."playlists" OWNER TO "postgres";

COMMENT ON COLUMN "public"."playlists"."name" IS 'Playlist name';

COMMENT ON COLUMN "public"."playlists"."short_id" IS 'Short ID for nicer URLs';

COMMENT ON COLUMN "public"."playlists"."deleted_at" IS 'Timestamp when playlist was soft deleted. NULL means not deleted.';

COMMENT ON COLUMN "public"."playlists"."duration_seconds" IS 'Total duration of playlist in seconds, automatically calculated';

COMMENT ON COLUMN "public"."playlists"."image_processing_updated_at" IS 'Timestamp when playlist image processing was last updated';

COMMENT ON COLUMN "public"."playlists"."image_processing_status" IS 'Status of playlist image processing (pending, processing, completed, failed)';

COMMENT ON COLUMN "public"."playlists"."image_url" IS 'URL to uploaded cropped playlist image in Supabase Storage (JPEG)';

COMMENT ON COLUMN "public"."playlists"."image_webp_url" IS 'URL to optimized WebP version of uploaded playlist image';

COMMENT ON COLUMN "public"."playlists"."image_avif_url" IS 'URL to optimized AVIF version of uploaded playlist image';

-- Playlist videos table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."playlist_videos" (
  "playlist_id" bigint NOT NULL,
  "video_id" text NOT NULL,
  "video_position" int2 DEFAULT NULL,
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."playlist_videos_id_seq" START
    WITH
      1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  )
);

ALTER TABLE "public"."playlist_videos" OWNER TO "postgres";

COMMENT ON COLUMN "public"."playlist_videos"."video_position" IS 'Ordering of videos added to playlist (1-indexed).';

-- Playlist videos constraints (no foreign keys)
ALTER TABLE ONLY "public"."playlist_videos"
ADD CONSTRAINT "playlist_videos_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."playlist_videos"
ADD CONSTRAINT "unique_playlist_video" UNIQUE ("playlist_id", "video_id");

-- Timestamps table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."timestamps" (
  "id" bigint NOT NULL,
  "user_id" uuid NOT NULL,
  "video_id" "text" NOT NULL,
  "video_start_seconds" numeric,
  "playlist_id" bigint,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  "watched_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  "sorted_by" "public"."playlist_sorted_by" DEFAULT NULL,
  "sort_order" "public"."playlist_sort_order" DEFAULT NULL
);

ALTER TABLE "public"."timestamps" OWNER TO "postgres";

COMMENT ON COLUMN "public"."timestamps"."video_start_seconds" IS 'Offset in seconds to start video playback.';

COMMENT ON COLUMN "public"."timestamps"."watched_at" IS 'Datetime for when the video was last watched.';

-- Timestamps constraints and identity (no foreign keys)
ALTER TABLE "public"."timestamps"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."user_video_timestamps_id_seq" START
  WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."timestamps"
ADD CONSTRAINT "user_video_timestamps_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."timestamps"
ADD CONSTRAINT "unique_user_video" UNIQUE ("user_id", "video_id");

-- Profiles table (without foreign keys initially) - FIXED TYPE REFERENCES
CREATE TABLE IF NOT EXISTS "public"."profiles" (
  "id" uuid NOT NULL,
  "username" text,
  "sources" "public"."source" [] DEFAULT ARRAY[
    'giantbomb',
    'jeffgerstmann',
    'nextlander',
    'remap'
  ]::"public"."source" [],
  "content_description" "public"."content_description" DEFAULT 'BRIEF',
  "content_display" "public"."content_display" DEFAULT 'TILES',
  "avatar_url" text DEFAULT NULL,
  "account_type" public.profile_account_type DEFAULT 'default',
  PRIMARY KEY ("id")
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

-- User playlists table (without foreign keys initially)
CREATE TABLE IF NOT EXISTS "public"."user_playlists" (
  "id" bigint NOT NULL,
  "user_id" uuid DEFAULT NULL,
  "playlist_position" int2 DEFAULT NULL,
  "sorted_by" "public"."playlist_sorted_by" DEFAULT 'playlistOrder' NOT NULL,
  "sort_order" "public"."playlist_sort_order" DEFAULT 'ascending' NOT NULL,
  "added_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" () NOT NULL,
  PRIMARY KEY ("id", "user_id")
);

ALTER TABLE "public"."user_playlists" OWNER TO "postgres";

COMMENT ON COLUMN "public"."user_playlists"."playlist_position" IS 'Ordering of playlists for each user (1-indexed).';
