-- Migration: 11_video_history_system.sql
-- Purpose: Create comprehensive video history tracking system
-- Dependencies: Requires base tables from 03_base_tables.sql (videos, timestamps)
-- This migration includes video history table, triggers, and RPC functions
-- ============================================================================
-- Create video_history table to track viewing analytics
CREATE TABLE IF NOT EXISTS "public"."video_history" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."video_history_id_seq" START
    WITH
      1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  ),
  "user_id" uuid NOT NULL,
  "video_id" text NOT NULL,
  "source" "public"."source" NOT NULL,
  "seconds_watched" numeric DEFAULT 0 NOT NULL,
  "session_start_time" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "session_end_time" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "public"."video_history" OWNER TO "postgres";

COMMENT ON TABLE "public"."video_history" IS 'Tracks user video viewing sessions and analytics';

COMMENT ON COLUMN "public"."video_history"."seconds_watched" IS 'Total seconds of actual video watched (excluding seeking/scrubbing)';

COMMENT ON COLUMN "public"."video_history"."session_start_time" IS 'When user started watching this video session';

COMMENT ON COLUMN "public"."video_history"."session_end_time" IS 'When user stopped watching this video session';

-- Add foreign key constraints
ALTER TABLE ONLY "public"."video_history"
ADD CONSTRAINT "video_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."video_history"
ADD CONSTRAINT "video_history_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos" ("id") ON DELETE CASCADE;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS "idx_video_history_user_id" ON "public"."video_history" USING btree ("user_id");

CREATE INDEX IF NOT EXISTS "idx_video_history_video_id" ON "public"."video_history" USING btree ("video_id");

CREATE INDEX IF NOT EXISTS "idx_video_history_session_start" ON "public"."video_history" USING btree ("session_start_time");

CREATE INDEX IF NOT EXISTS "idx_video_history_user_video" ON "public"."video_history" USING btree ("user_id", "video_id");

-- Enable Row Level Security (RLS)
ALTER TABLE "public"."video_history" ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only access their own video history
CREATE POLICY "Users can access their own video history" ON "public"."video_history" FOR ALL USING (auth.uid () = user_id);

-- ============================================================================
-- TRIGGER FUNCTIONS
-- ============================================================================
-- Function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION "public"."update_video_history_updated_at" () RETURNS TRIGGER LANGUAGE plpgsql
SET
  search_path = '' AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Trigger to update updated_at on video_history updates
CREATE TRIGGER "trigger_update_video_history_updated_at" BEFORE
UPDATE ON "public"."video_history" FOR EACH ROW
EXECUTE FUNCTION "public"."update_video_history_updated_at" ();

-- ============================================================================
-- RPC FUNCTIONS FOR VIDEO HISTORY
-- ============================================================================
-- Function to record video history session
CREATE OR REPLACE FUNCTION "public"."record_video_history" (
  p_video_id text,
  p_seconds_watched numeric DEFAULT 0,
  p_session_start_time TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  p_session_end_time TIMESTAMP WITH TIME ZONE DEFAULT NULL
) RETURNS TABLE (
  id bigint,
  user_id uuid,
  video_id text,
  source "public"."source",
  seconds_watched numeric,
  session_start_time TIMESTAMP WITH TIME ZONE,
  session_end_time TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
) LANGUAGE plpgsql
SET
  search_path = '' AS $$
DECLARE
  current_user_id uuid;
  video_source "public"."source";
BEGIN
  -- Get the current user ID from auth context
  current_user_id := auth.uid();
  
  -- Check if user is authenticated
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTHENTICATION_REQUIRED: User must be authenticated to record video history'
      USING ERRCODE = 'P0001';
  END IF;

  -- Get video source
  SELECT v.source INTO video_source
  FROM public.videos v
  WHERE v.id = p_video_id;

  -- Check if video exists
  IF video_source IS NULL THEN
    RAISE EXCEPTION 'VIDEO_NOT_FOUND: Video with id % not found', p_video_id
      USING ERRCODE = 'P0002';
  END IF;

  -- Insert video history record
  INSERT INTO public.video_history (
    user_id,
    video_id,
    source,
    seconds_watched,
    session_start_time,
    session_end_time
  )
  VALUES (
    current_user_id,
    p_video_id,
    video_source,
    COALESCE(p_seconds_watched, 0),
    COALESCE(p_session_start_time, now()),
    p_session_end_time
  );

  -- Return the created record
  RETURN QUERY
  SELECT
    vh.id,
    vh.user_id,
    vh.video_id,
    vh.source,
    vh.seconds_watched,
    vh.session_start_time,
    vh.session_end_time,
    vh.created_at,
    vh.updated_at
  FROM public.video_history vh
  WHERE vh.user_id = current_user_id 
    AND vh.video_id = p_video_id
    AND vh.session_start_time = COALESCE(p_session_start_time, vh.session_start_time)
  ORDER BY vh.created_at DESC
  LIMIT 1;
END;
$$;

-- Function to update existing video history session
CREATE OR REPLACE FUNCTION "public"."update_video_history_session" (
  p_history_id bigint,
  p_seconds_watched numeric DEFAULT NULL,
  p_session_end_time TIMESTAMP WITH TIME ZONE DEFAULT NULL
) RETURNS TABLE (
  id bigint,
  user_id uuid,
  video_id text,
  source "public"."source",
  seconds_watched numeric,
  session_start_time TIMESTAMP WITH TIME ZONE,
  session_end_time TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
) LANGUAGE plpgsql
SET
  search_path = '' AS $$
DECLARE
  current_user_id uuid;
BEGIN
  -- Get the current user ID from auth context
  current_user_id := auth.uid();
  
  -- Check if user is authenticated
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTHENTICATION_REQUIRED: User must be authenticated to update video history'
      USING ERRCODE = 'P0001';
  END IF;

  -- Update the video history record
  UPDATE public.video_history
  SET 
    seconds_watched = CASE 
      WHEN p_seconds_watched IS NOT NULL THEN p_seconds_watched
      ELSE seconds_watched
    END,
    session_end_time = CASE 
      WHEN p_session_end_time IS NOT NULL THEN p_session_end_time
      ELSE session_end_time
    END,
    updated_at = now()
  WHERE id = p_history_id 
    AND user_id = current_user_id;

  -- Return the updated record
  RETURN QUERY
  SELECT
    vh.id,
    vh.user_id,
    vh.video_id,
    vh.source,
    vh.seconds_watched,
    vh.session_start_time,
    vh.session_end_time,
    vh.created_at,
    vh.updated_at
  FROM public.video_history vh
  WHERE vh.id = p_history_id 
    AND vh.user_id = current_user_id;
END;
$$;

-- Function to get user video history
CREATE OR REPLACE FUNCTION "public"."get_user_video_history" (
  p_video_id text DEFAULT NULL,
  p_limit integer DEFAULT 50,
  p_offset integer DEFAULT 0
) RETURNS TABLE (
  id bigint,
  user_id uuid,
  video_id text,
  source "public"."source",
  seconds_watched numeric,
  session_start_time TIMESTAMP WITH TIME ZONE,
  session_end_time TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  video_title text,
  video_duration text,
  video_thumbnail_url text
) LANGUAGE plpgsql
SET
  search_path = '' AS $$
DECLARE
  current_user_id uuid;
BEGIN
  -- Get the current user ID from auth context
  current_user_id := auth.uid();
  
  -- Check if user is authenticated
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTHENTICATION_REQUIRED: User must be authenticated to get video history'
      USING ERRCODE = 'P0001';
  END IF;

  -- Return video history with video details
  RETURN QUERY
  SELECT
    vh.id AS id,
    vh.user_id AS user_id,
    vh.video_id AS video_id,
    vh.source AS source,
    vh.seconds_watched AS seconds_watched,
    vh.session_start_time AS session_start_time,
    vh.session_end_time AS session_end_time,
    vh.created_at AS created_at,
    vh.updated_at AS updated_at,
    v.title AS video_title,
    v.duration AS video_duration,
    v.thumbnail_url AS video_thumbnail_url
  FROM public.video_history vh
  JOIN public.videos v ON vh.video_id = v.id
  WHERE vh.user_id = current_user_id
    AND (p_video_id IS NULL OR vh.video_id = p_video_id)
  ORDER BY vh.session_start_time DESC
  LIMIT p_limit
  OFFSET p_offset;
END;
$$;

-- Function to get video analytics for user
CREATE OR REPLACE FUNCTION "public"."get_video_analytics" (
  p_video_id text DEFAULT NULL,
  p_days_back integer DEFAULT 30
) RETURNS TABLE (
  video_id text,
  video_title text,
  total_sessions bigint,
  total_seconds_watched numeric,
  average_session_length numeric,
  last_watched TIMESTAMP WITH TIME ZONE,
  first_watched TIMESTAMP WITH TIME ZONE
) LANGUAGE plpgsql
SET
  search_path = '' AS $$
DECLARE
  current_user_id uuid;
  start_date TIMESTAMP WITH TIME ZONE;
BEGIN
  -- Get the current user ID from auth context
  current_user_id := auth.uid();
  
  -- Check if user is authenticated
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTHENTICATION_REQUIRED: User must be authenticated to get video analytics'
      USING ERRCODE = 'P0001';
  END IF;

  -- Calculate start date for analytics period
  start_date := now() - INTERVAL '1 day' * p_days_back;

  -- Return aggregated analytics
  RETURN QUERY
  SELECT
    vh.video_id AS video_id,
    v.title AS video_title,
    COUNT(vh.id) AS total_sessions,
    SUM(vh.seconds_watched) AS total_seconds_watched,
    AVG(vh.seconds_watched) AS average_session_length,
    MAX(vh.session_start_time) AS last_watched,
    MIN(vh.session_start_time) AS first_watched
  FROM public.video_history vh
  JOIN public.videos v ON vh.video_id = v.id
  WHERE vh.user_id = current_user_id
    AND vh.session_start_time >= start_date
    AND (p_video_id IS NULL OR vh.video_id = p_video_id)
  GROUP BY vh.video_id, v.title
  ORDER BY SUM(vh.seconds_watched) DESC;
END;
$$;

-- ============================================================================
-- TRIGGER TO AUTO-RECORD HISTORY WHEN TIMESTAMPS UPDATE
-- ============================================================================
-- Function to automatically record video history when timestamps are updated
CREATE OR REPLACE FUNCTION "public"."auto_record_video_history" () RETURNS TRIGGER LANGUAGE plpgsql
SET
  search_path = '' AS $$
DECLARE
  video_source "public"."source";
  watch_duration numeric;
BEGIN
  -- Only proceed if this is an INSERT or UPDATE with meaningful changes
  IF TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND (
    OLD.video_start_seconds IS DISTINCT FROM NEW.video_start_seconds OR
    OLD.watched_at IS DISTINCT FROM NEW.watched_at
  )) THEN
    
    -- Get video source
    SELECT v.source INTO video_source
    FROM public.videos v
    WHERE v.id = NEW.video_id;

    -- Calculate estimated watch duration based on timestamp changes
    -- This is a simplified calculation - actual implementation would track real play time
    watch_duration := 0;
    
    IF NEW.video_start_seconds IS NOT NULL AND NEW.video_start_seconds > 0 THEN
      -- If there's a meaningful timestamp, estimate some watch time
      watch_duration := LEAST(30, NEW.video_start_seconds); -- Cap at 30 seconds estimation
    END IF;

    -- Record video history session (non-blocking)
    BEGIN
      INSERT INTO public.video_history (
        user_id,
        video_id,
        source,
        seconds_watched,
        session_start_time,
        session_end_time
      )
      VALUES (
        NEW.user_id,
        NEW.video_id,
        video_source,
        watch_duration,
        COALESCE(NEW.watched_at, now()),
        NEW.watched_at
      );
    EXCEPTION
      WHEN OTHERS THEN
        -- Log error but don't fail the timestamp update
        RAISE WARNING 'Failed to auto-record video history: %', SQLERRM;
    END;
  END IF;

  RETURN NEW;
END;
$$;

-- Trigger to auto-record history when timestamps are updated
CREATE TRIGGER "trigger_auto_record_video_history"
AFTER INSERT
OR
UPDATE ON "public"."timestamps" FOR EACH ROW
EXECUTE FUNCTION "public"."auto_record_video_history" ();
